extends Area3D
signal falling_obj(size:float)
var obj_dict = {
	"wall_orderwindow":10,
	"wall_orderwindow_decorated":10,
	"wall_window_closed":10,
	"wall_window_open":10,
	"bowl":1,
	"bowl_dirty":1,
	"bowl_small":1,
	"chair_A":2,
	"chair_B":2,
	"chair_stool":2,
	"crate":8,
	"crate_buns":8,
	"crate_carrots":8,
	"crate_cheese":8,
	"crate_ham":8,
	"crate_lettuce":8,
	"crate_lid":8,
	"crate_onions":8,
	"crate_potatoes":8,
	"crate_steak":8,
	"crate_tomatoes":8,
	"cuttingboard":1,
	"dishrack":2,
	"dishrack_plates":2,
	"door_A":5,
	"door_B":5,
	"extractorhood":10,
	"floor_kitchen":10,
	"floor_kitchen_small":5,
	"food_burger":1,
	"food_dinner":1,
	"food_ingredient_bun":1,
	"food_ingredient_bun_bottom":1,
	"food_ingredient_bun_top":1,
	"food_ingredient_burger_cooked":1,
	"food_ingredient_burger_trash":1,
	"food_ingredient_burger_uncooked":1,
	"food_ingredient_carrot":1,
	"food_ingredient_carrot_chopped":1,
	"food_ingredient_carrot_pieces":1,
	"food_ingredient_cheese":1,
	"food_ingredient_cheese_chopped":1,
	"food_ingredient_cheese_slice":1,
	"food_ingredient_ham":1,
	"food_ingredient_ham_cooked":1,
	"food_ingredient_ham_trash":1,
	"food_ingredient_lettuce":1,
	"food_ingredient_lettuce_chopped":1,
	"food_ingredient_lettuce_slice":1,
	"food_ingredient_onion":1,
	"food_ingredient_onion_chopped":1,
	"food_ingredient_onion_rings":1,
	"food_ingredient_potato":1,
	"food_ingredient_potato_chopped":1,
	"food_ingredient_potato_mashed":1,
	"food_ingredient_steak":1,
	"food_ingredient_steak_pieces":1,
	"food_ingredient_tomato":1,
	"food_ingredient_tomato_slice":1,
	"food_ingredient_tomato_slices":1,
	"food_ingredient_vegetableburger_cooked":2,
	"food_ingredient_vegetableburger_uncooked":2,
	"food_stew":2,
	"food_vegetableburger":2,
	"fridge_A":8,
	"fridge_A_decorated":8,
	"fridge_B":8,
	"jar_A_large":2,
	"jar_A_medium":1,
	"jar_A_small":1,
	"jar_B_large":2,
	"jar_B_medium":1,
	"jar_B_small":1,
	"jar_C_large":2,
	"jar_C_medium":1,
	"jar_C_small":1,
	"jar_D_large":2,
	"jar_D_medium":1,
	"jar_D_small":1,
	"ketchup":1,
	"kitchencabinet":5,
	"kitchencabinet_corner":5,
	"kitchencabinet_corner_half":5,
	"kitchencabinet_half":5,
	"kitchencounter_innercorner":5,
	"kitchencounter_innercorner_backsplash":5,
	"kitchencounter_outercorner":5,
	"kitchencounter_outercorner_backsplash":5,
	"kitchencounter_sink":5,
	"kitchencounter_sink_backsplash":5,
	"kitchencounter_straight_A":5,
	"kitchencounter_straight_A_backsplash":5,
	"kitchencounter_straight_A_decorated":5,
	"kitchencounter_straight_B":5,
	"kitchencounter_straight_B_backsplash":5,
	"kitchencounter_straight_decorated":5,
	"kitchentable_A":5,
	"kitchentable_A_large":8,
	"kitchentable_A_large_decorated":8,
	"kitchentable_B":5,
	"kitchentable_B_large":8,
	"kitchentable_sink":5,
	"kitchentable_sink_large":8,
	"kitchentable_sink_large_decorated":8,
	"knife":1,
	"lid_A":1,
	"lid_B":1,
	"lid_large":2,
	"menu":1,
	"mustard":1,
	"oven":5,
	"pan_006":1,
	"pan_A":1,
	"pan_B":1,
	"papertowel":1,
	"pillar_A":1,
	"pillar_B":1,
	"plate":1,
	"plate_dirty":1,
	"plate_small":1,
	"pot_A":2,
	"pot_A_stew":2,
	"pot_B":2,
	"pot_B_stew":2,
	"pot_large":2,
	"shelf_papertowel":2,
	"shelf_papertowel_decorated":2,
	"stew_bowl":1,
	"stew_pot":2,
	"stove_multi":6,
	"stove_multi_countertop":6,
	"stove_multi_decorated":6,
	"stove_single":6,
	"stove_single_countertop":6,
	"table_round_A":7,
	"table_round_A_decorated":7,
	"table_round_A_small":4,
	"table_round_A_small_decorated":4,
	"table_round_B":7,
	"towelrail":1,
	"wall":8,
	"wall_decorated":8,
	"wall_doorway":8,
	"wall_half":8,

}

# Called when the node enters the scene tree for the first time.
func _ready():
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass


func _on_body_entered(body):
	if obj_dict.has(body.name):
		falling_obj.emit(obj_dict[body.name])
	body.queue_free()
	
	
	
	
	
	
	
	
	
	
	
	
	
